### ISSUE TITLE
How can I get started with Xperia Z development ?

### ISSUE THREAD

**Issue by orgicus** [sonyxperiadev/device-sony-yuga#6]
Hello,

I'm trying to use some of the Xperia Z features like the camera burst mode and I'm not finding the instructions easy to follow.

I did 
- initialize a repo as instructed android source instructions(http://source.android.com/source/downloading.html). (Maybe user should be warned that it takes a while to download ~15.83 GB)
- place the provided xml snippet under .repo/local_manifests/c6603.xml
- downloaded and unzipped vendor binaries
- ran repo sync
- got confused trying this:

```
lunch full_c6603-userdebug
```

I'm guessing lunch is a typo, should be launch ?
If so, launch what and how ? Is there a launch command ? If so, where ?

I did try running make anyway, but got this:

```
============================================
PLATFORM_VERSION_CODENAME=AOSP
PLATFORM_VERSION=4.2.2.2.2.2.2.2.2.2
TARGET_PRODUCT=full
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86
HOST_OS=darwin
HOST_OS_EXTRA=Darwin-12.0.0-x86_64-i386-64bit
HOST_BUILD_TYPE=release
BUILD_ID=OPENMASTER
OUT_DIR=out
============================================
Checking build tools versions...
build/core/main.mk:100: ************************************************************
build/core/main.mk:101: You are building on a case-insensitive filesystem.
build/core/main.mk:102: Please move your source tree to a case-sensitive filesystem.
build/core/main.mk:103: ************************************************************
build/core/main.mk:104: *** Case-insensitive filesystems not supported.  Stop.
```

I'm using OSX 10.8. What do I need to do to get a HelloWorld project running on XperiaZ ? How can I set/trigger the camera burst mode ?

Update:
I've commented out the makefile lines related to the case-insensitive filesystem:

```
ifneq ($(HOST_OS),windows)
ifneq ($(HOST_OS)-$(HOST_ARCH),darwin-ppc)
# check for a case sensitive file system
# ifneq (a,$(shell mkdir -p $(OUT_DIR) ; \
#                 echo a > $(OUT_DIR)/casecheck.txt; \
#                     echo B > $(OUT_DIR)/CaseCheck.txt; \
#                 cat $(OUT_DIR)/casecheck.txt))
# $(warning ************************************************************)
# $(warning You are building on a case-insensitive filesystem.)
# $(warning Please move your source tree to a case-sensitive filesystem.)
# $(warning ************************************************************)
# $(error Case-insensitive filesystems not supported)
# endif
endif
endif
```

and carried on with the build but ran into another error while building libsdl:

```
host ObjC: emulator-arm <= external/qemu/distrib/sdl-1.2.15/src/main/macosx/SDLMain.m
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:24,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:70,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from external/qemu/distrib/sdl-1.2.15/src/main/macosx/SDLMain.h:11,
                 from external/qemu/distrib/sdl-1.2.15/src/main/macosx/SDLMain.m:9:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Security.framework/Headers/cssmconfig.h:73: error: conflicting types for ‘uint16’
external/qemu/fpu/softfloat.h:60: error: previous declaration of ‘uint16’ was here
make: *** [out/host/darwin-x86/obj/EXECUTABLES/emulator-arm_intermediates/distrib/sdl-1.2.15/src/main/macosx/SDLMain.o] Error 1
```

How can I get past this issue ? I'm using osx 10.8 and have both sdks installed(10.7 and 10.8). 
Why is it defaulting to 10.7 ?

Is there a prebuilt/add-on version of libcameraservice ? If so, where can I find it and use it ?

Yet another update:
After reading this post(http://stackoverflow.com/questions/6282669/how-do-you-create-a-loadable-kernel-module-for-android) I've used:

```
source build/envsetup.sh
```

and after that `lunch full_c6603-userdebug` worked this time.

Update ! I've finally compiled AOSP

I've tweaked a few more makefiles to carry on, for

build/target/product/emulator.mk

I commented out the emulator:

```
# PRODUCT_PACKAGES += \
#   emulator \
#   emulator-x86 \
#   emulator-arm \
#   emulator-mips \
#   emulator64-x86 \
#   emulator64-arm \
#   emulator64-mips \
#   libOpenglRender \
#   libGLES_CM_translator \
#   libGLES_V2_translator \
#   libEGL_translator \
#   lib64OpenglRender \
#   lib64GLES_CM_translator \
#   lib64GLES_V2_translator \
#   lib64EGL_translator
```

and left in the other packages. I wasn't planning to use the emulator anyway since from my experience so far the Android Emulator is pretty slow(unless I'm using it wrong).

Also in build/target/product/base.mk

I've moved the camera related libraries to the top just in case, like so:

```
PRODUCT_PACKAGES += \
    libcamera_client \
    libcameraservice \
    20-dns.conf \
    95-configured \
    am \
    android.policy \
    android.test.runner \
    app_process \
    applypatch \
    bmgr \
    bugreport \
    content \
    dbus-daemon \
    dhcpcd \
    dhcpcd-run-hooks \
    dnsmasq \
    framework \
    fsck_msdos \
    ime \
    javax.obex \
    libSR_AudioIn \
    libandroid \
    libandroid_runtime \
    libandroid_servers \
    libaudioeffect_jni \
    libaudioflinger \
    libbundlewrapper \
    libchromium_net \
    libdbus \
    libdl \
    libdrm1 \
    libdrm1_jni \
    libeffects \
    libiprouteutil \
    libjni_latinime \
    libjnigraphics \
    libmedia \
    libmedia_jni \
    libmediaplayerservice \
    libmtp \
    libnetlink \
    libnetutils \
    libreference-ril \
    libreverbwrapper \
    libril \
    librtp_jni \
    libsensorservice \
    libskia \
    libsonivox \
    libsoundpool \
    libsqlite \
    libstagefright \
    libstagefright_amrnb_common \
    libstagefright_avc_common \
    libstagefright_enc_common \
    libstagefright_foundation \
    libstagefright_omx \
    libstagefright_yuv \
    libsystem_server \
    libusbhost \
    libutils \
    libvisualizer \
    libvorbisidec \
    libwebcore \
    libwpa_client \
    mediaserver \
    monkey \
    mtpd \
    ndc \
    netcfg \
    netd \
    ping \
    platform.xml \
    pppd \
    pm \
    racoon \
    run-as \
    schedtest \
    screenshot \
    sdcard \
    services \
    settings \
    svc \
    system_server \
    tc \
    vdc \
    vold

$(call inherit-product, $(SRC_TARGET_DIR)/product/embedded.mk)
```

So these libraries I'm interested in got compiled:

```
libcamera_client.so
libcamera_metadata.so
libcameralight.so
libcameraservice.so
```

Wondering how to use them though for the camere burst mode feature.

Another update:

I've just got started with the NDK and attempted to instantiate BurstCapture using JNI.
So far I've got a java class:

``` java

package com.hirschandmann.snap;

    import android.util.Log;

    public class CamLib {
        private static final String TAG = "CamLib";

        public static void sayHi(){
            Log.d(TAG,"CamLib says hi");
        }
        public native static int testCam();

        static{
            try{
                System.loadLibrary("cameraservice");
                Log.d(TAG,"loaded cameraservice");
            }catch(UnsatisfiedLinkError e){
                Log.d(TAG,"failed to load cameraservice");
                Log.d(TAG,e.getMessage());
            }
            try{
                System.loadLibrary("com_hirschandmann_snap_CamLib");
                Log.d(TAG,"loaded CamLib");
            }catch(UnsatisfiedLinkError e){
                Log.d(TAG,"failed to load CamLib");
                Log.d(TAG,e.getMessage());
            }
        }

    }


```

and a c++ class:

``` c++

#include <jni.h>
#include <android/log.h>
#include "camera2/BurstCapture.h"
#include "utils/Vector.h"

namespace com_hirschandmann_snap{

    using namespace android;

    static int testCam(JNIEnv * env, jclass clazz){
        android::camera2::BurstCapture bc(android::wp<android::Camera2Client>, android::wp<android::camera2::CaptureSequencer>);
        Vector<android::camera2::CameraMetadata> metadatas;
        //bc.start();
        __android_log_print(ANDROID_LOG_DEBUG,"CamLib.cpp","testCam()");
        return 1;
    }
    //mapping
    static JNINativeMethod method_table[] = {
            {"testCam","()I",(void *)testCam}
    };
}
using namespace com_hirschandmann_snap;

extern "C" jint JNI_OnLoad(JavaVM* vm, void* reserved)
{
    JNIEnv* env;
    if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }else{
        jclass clazz = env->FindClass("com/hirschandmann/snap/CamLib");
        if(clazz){
            env->RegisterNatives(clazz,method_table,sizeof(method_table)/sizeof(method_table[0]));
            env->DeleteLocalRef(clazz);
            return JNI_VERSION_1_6;
        }else{
            return -1;
        }
    }

    // Get jclass with env->FindClass.
    // Register methods with env->RegisterNatives.

    return JNI_VERSION_1_6;
}

```

Instantiating BurstCapture seems to work, but I get errors when I try to make a vector of CameraMetadata objects:

```
/Users/hm/Documents/adt-bundle-mac-x86_64-20130219/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/com_hirschandmann_snap_CamLib/com_hirschandmann_snap_CamLib.o: in function android::Vector<android::camera2::CameraMetadata>::do_copy(void*, void const*, unsigned int) const:jni/utils/TypeHelpers.h:154: error: undefined reference to 'android::camera2::CameraMetadata::CameraMetadata(android::camera2::CameraMetadata const&)'
```

I'm a bit stuck at the moment on this route.
Also, I used `adb pull` to get the camera related libraries from an actual Xperia Z phone and noticed there are a few libraries that I didn't find in AOSP: libcamera_clientsemc.so,libcameraextensionclient.so and libcameraextensionjni.so. The last two I'm suspecting are what I might need/what the Xperia version of the Camera application might use to also include the Burst mode. 

Having access to the Xperia Z version of the Camera application source code (rather than the default AOSP shipped generic Android Camera application) would make this task a lot easier.

Any sort of support/hints would help.

Thank you,
George

**Comment by andersson** [comment]
Hi, I used to build Android on OSX but as it's barely supported by Google, so I gave up on it. Also it's strongly recommended that you build on a file system that is case sensitive, instead of fixing the build system.

We have not yet published the camera HAL for the Xperia Z, so you will have a bunch of work to reproduce a platform with working camera support.

May I ask what kind of development you're trying to do?

**Comment by orgicus** [comment]
Hello Björn,

I appreciate taking your time to help.

I've managed to compile AOSP sans the emulator(due to the sdl errors (although in isolation the provided sdl compiled fine)) and have also checked the source code for the Camera application but it looks like the standard
Android camera application source, not the Xperia Z shipped one with the burst feature. 
Can I download the source code for the shipped Camera application ? How was that made ?

What are my alternatives at this point to use the feature ?
Would it be possible to tap into libcameraservice.so via the NDK/JNI and use the BurstCapture and related classes ? What do you recommend / what would the best approach be ?

I am currently prototyping that might involve a large number of xperia phones simultaneously being triggered to take photos in Burst Mode. Is there a way at least to script/automate the Camera app somehow to trigger a burst shoot on request ? 

Thank you!

**Comment by andersson** [comment]
Let's continue to discuss your specific question in a separate forum.

Regarding the generic questions on camera, we're working with the involved parties on trying to provide a fully functional camera solution as part of our AOSP build.
